### ISSUE TITLE
Refresh Github runner on startup?

### ISSUE THREAD

**Issue by RafaelGSS** [nodesource/aws-eco-runner#5]
I'm using `nodesource/aws-eco-runner` on https://github.com/RafaelGSS/nodejs-bench-operations and it seems the runner never gets online for some reason. See: https://github.com/RafaelGSS/nodejs-bench-operations/actions/runs/9331589683/job/25686446337

It succeeded in the action _start_: 
![image](https://github.com/nodesource/aws-eco-runner/assets/26234614/585bbaf8-44a5-4011-8091-45977ee02a26)

But the runner never gets online:

![image](https://github.com/nodesource/aws-eco-runner/assets/26234614/43be2621-1e54-41a8-b358-f1d598a99b9f)

cc: @riosje

**Comment by riosje** [comment]
@RafaelGSS could you check the runner is still registered?

**Comment by riosje** [comment]
The issue was due the host ran out of disk, then the runner service was not able to start and github eventually end up de-registering the runner.
